name: Integration
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4

       - name: "Create version number"
         run: |
          echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV
          echo ${{ env.APP_VERSION }}

       - name: Install Dependencies
         run: npm install 

       - name: "Logs into docker"
         uses: docker/login-action@v3
         with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Set up Minikube
         uses: medyagh/setup-minikube@latest
         id: minikube
         with:
           minikube version: 'v1.24.0'
           kubernetes version: 'v1.24.0'
           driver: none

       - name: Start Minikube
         run: |
            sudo minikube start --driver=none

       - name: "Build our Code"
         env:
            IMAGE_NAME: calapp
            VERSION: ${{ env.APP_VERSION }}
            USERNAME: epauldike
         run: |
             docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
             docker push $USERNAME/$IMAGE_NAME:$VERSION

       - name: "Install Helm"
         uses: azure/setup-helm@v4.2.0
         id: "install-helm"

       - name: "deploy helm"
         run: |
          helm upgrade --install deployment.yaml /home/pdyke/new/deployment.yaml --set image.tag=${{ env.APP_VERSION }}
