name: Integration
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-north-1

       - name: "Create version number"
         run: |
          echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV
          echo ${{ env.APP_VERSION }}

       - name: Install Dependencies
         run: npm install 

       - name: "Logs into docker"
         uses: docker/login-action@v3
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: "Build our Code"
         env:
            IMAGE_NAME: calapp
            VERSION: ${{ env.APP_VERSION }}
            USERNAME: epauldike
         run: |
             docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
             docker push $USERNAME/$IMAGE_NAME:$VERSION

       - name: Update kube-config
         run: aws eks update-kubeconfig --name education-eks-cKFm6ii9 --region eu-north-1

       - name: Install kubectl
         uses: azure/setup-kubectl@v3
         with:
           version: 'v1.24.0' # default is latest stable
           id: install

       - name: "Install Helm"
         uses: azure/setup-helm@v4.2.0
         id: "install-helm" 
         
      #  - name: "Install Prometheus"
      #    run: |
      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      #     helm repo update
      #     helm install prometheus prometheus-community/prometheus

       - name: Create Helm chart
         run: |
          helm create mychart

       - name: "Delete Templates"
         run: | 
          rm -rf mychart/templates/tests/*
          rm -rf mychart/templates/NOTES.txt
          rm -rf mychart/templates/deployment.yaml
          rm -rf mychart/templates/service.yaml
          rm -rf mychart/templates/ingress.yaml
          rm -rf mychart/templates/hpa.yaml
          rm -rf mychart/templates/serviceaccount.yaml
          rm -rf mychart/templates/_helpers.tpl

       - name: "Add to Templates"
         run: |
          cp /home/pdyke/new/deployment.yaml mychart/templates

       - name: "deploy helm"
         run: |
          helm upgrade --install mychart mychart --set image.tag=${{ env.APP_VERSION }}

      #  - name: "Install Grafana"
      #    run: |
      #     helm repo add grafana https://grafana.github.io/helm-charts
      #     helm repo update
      #     helm install grafana grafana/grafana


        